- name: Determine if Netplan is used
  fail:
    msg: "Only Netplan capable hosts are supported"
  when: not (ansible_distribution == 'Ubuntu' or (ansible_distribution == 'Debian' and ansible_distribution_version is version('12', '>=')))

- name: Generate Netplan configuration
  template:
    src: "50-cloud-init.yaml.j2"
    dest: "{{ netplan_config_file }}"
  notify: Apply Netplan configuration
