- name: prepare interface configuration
  set_fact:
    kypo_interface_config:
      if: '{{ kypo_interface_device }}'
      ipaddr: dhcp
      mtu: '{{ kypo_interface_mtu }}'
      enable: 1

- name: configure interface
  xml:
    path: '{{ kypo_interface_opnsense_local_config_file }}'
    xpath: '/opnsense/interfaces/{{ kypo_interface_device }}/{{ item.key }}'
    value: '{{ item.value }}'
    pretty_print: yes
  delegate_to: localhost
  loop: '{{ kypo_interface_config | dict2items }}'
