
- name: configure interface
  blockinfile:
      path: '{{ kypo_interface_file }}'
      create: yes
      marker: '# {mark} {{ kypo_interface_device }}'
      block: |
          allow-hotplug {{ kypo_interface_device }}
          auto {{ kypo_interface_device }}
          iface {{ kypo_interface_device }} inet dhcp
              mtu {{ kypo_interface_mtu }}
              {% if kypo_interface_default_gateway -%}
              gateway {{ kypo_interface_default_gateway }}
              up route add default gw {{ kypo_interface_default_gateway }}
              {% endif -%}
              {% if kypo_interface_routes -%}
              {% for route in kypo_interface_routes -%}
              post-up ip route add {{ route['network'] }}/{{ route['mask'] }} via {{ route['gateway'] }}
              pre-down ip route del {{ route['network'] }}/{{ route['mask'] }} via {{ route['gateway'] }}
              {% endfor %}
              {% endif %}
  notify: kypo_interface_networking_restart

