
- name: check existence of required variables
  fail:
      msg: kypo_interface_mac is not defined
  when: not kypo_interface_mac

- set_fact:
      kypo_interface_device: '{%- from "roles/kypo-common/templates/network.j2" import mac_to_interface with context -%}
                         {{ mac_to_interface(kypo_interface_mac) | default("") }}'

- include: clean.yml
  when: kypo_interface_clean is defined and kypo_interface_clean

- include: interface.yml

