- name: check existence of required variables
  fail:
    msg: required variable '{{ item.key }}' is undefined
  when: item.value is undefined or not item.value
  with_dict: '{{ interface_required_variables }}'

- name: check existence of required variables
  fail:
    msg: interface_interfaces has an item with undefined interface_mac or interface_device
  when: |
    (interface_interfaces | rejectattr('interface_mac', 'defined') | length > 0) or
    (interface_interfaces | rejectattr('interface_device', 'defined') | length > 0)

- include_tasks: '{{ ansible_facts.os_family }}.yml'
